#!/bin/bash -eu

readonly version=1.0.0
readonly gistim_home=${GISTIM_HOME:-$HOME/gistim}

mkdir -p "$gistim_home"

for arg in "$@"; do
  [ "$arg" = '--list' ] && find "$gistim_home" -type d -maxdepth 1 && exit
  [ "$arg" = '--path' ] && echo "$gistim_home" && exit
  [ "$arg" = '--version' ] && echo gistimnnow "$version" && exit
done

permitted_options=''
pushd "$gistim_home" >/dev/null
  for arg in "$@"; do
    [[ "$arg" =~ ^[^-].+$ ]] && $permitted_options="$permitted_options $arg"
  done
  
  readonly created=$(gistim create $permitted_options)
  readonly gist_local_path=$(echo "$created" | tail -n 1)

  return_to_current_directory=true
popd > /dev/null

echo "$gist_local_path"

