#!/usr/bin/env ruby

require 'pry'
require 'gistim'

subcommand = ARGV[0]

if subcommand == 'clone'
  Gistim::Clone.clone(ARGV[1], clone_directory: ARGV[2])
elsif subcommand == 'create'
  Gistim::Create.new(alias_name: ARGV[1]).create
else
  puts <<~TEXT
    =====================================
      $ gistim command delegated to $ gist command
    =====================================
  TEXT
  puts `gist #{ARGV.join(' ')}`
end

