#!/usr/bin/env ruby

require 'gistim'

subcommand = ARGV[0]

if subcommand == 'clone'
  Gistim::Clone.clone(ARGV[1], clone_directory: ARGV[2])
elsif subcommand == 'create'
  Gistim.implement(directory_name: ARGV[1])
else
  raise "Unknown subcommand #{subcommand}"
end

